// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//msgNo=11
type Error struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Error) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

//msgNo=12
type Success struct {
	Ok                   string   `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetOk() string {
	if m != nil {
		return m.Ok
	}
	return ""
}

//心跳协议
// msgNo=1
type HbReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HbReq) Reset()         { *m = HbReq{} }
func (m *HbReq) String() string { return proto.CompactTextString(m) }
func (*HbReq) ProtoMessage()    {}
func (*HbReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *HbReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HbReq.Unmarshal(m, b)
}
func (m *HbReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HbReq.Marshal(b, m, deterministic)
}
func (m *HbReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HbReq.Merge(m, src)
}
func (m *HbReq) XXX_Size() int {
	return xxx_messageInfo_HbReq.Size(m)
}
func (m *HbReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HbReq.DiscardUnknown(m)
}

var xxx_messageInfo_HbReq proto.InternalMessageInfo

// msgNo=2
type HbRes struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Zone                 string   `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HbRes) Reset()         { *m = HbRes{} }
func (m *HbRes) String() string { return proto.CompactTextString(m) }
func (*HbRes) ProtoMessage()    {}
func (*HbRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *HbRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HbRes.Unmarshal(m, b)
}
func (m *HbRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HbRes.Marshal(b, m, deterministic)
}
func (m *HbRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HbRes.Merge(m, src)
}
func (m *HbRes) XXX_Size() int {
	return xxx_messageInfo_HbRes.Size(m)
}
func (m *HbRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HbRes.DiscardUnknown(m)
}

var xxx_messageInfo_HbRes proto.InternalMessageInfo

func (m *HbRes) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *HbRes) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Success)(nil), "proto.Success")
	proto.RegisterType((*HbReq)(nil), "proto.HbReq")
	proto.RegisterType((*HbRes)(nil), "proto.HbRes")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xe6, 0x5c, 0xac,
	0xae, 0x45, 0x45, 0xf9, 0x45, 0x42, 0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x90, 0x04, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a,
	0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xab, 0x24, 0xc9, 0xc5, 0x1e, 0x5c,
	0x9a, 0x9c, 0x9c, 0x5a, 0x5c, 0x2c, 0xc4, 0xc7, 0xc5, 0x94, 0x9f, 0x0d, 0xd6, 0xc7, 0x19, 0xc4,
	0x94, 0x9f, 0xad, 0xc4, 0xce, 0xc5, 0xea, 0x91, 0x14, 0x94, 0x5a, 0xa8, 0xa4, 0x0f, 0x61, 0x14,
	0x0b, 0x09, 0x71, 0xb1, 0x94, 0x64, 0xe6, 0xa6, 0x82, 0xd5, 0x30, 0x07, 0x81, 0xd9, 0x20, 0xb1,
	0xaa, 0xfc, 0xbc, 0x54, 0xa8, 0xb9, 0x60, 0xb6, 0x13, 0x4b, 0x14, 0x53, 0x41, 0x52, 0x12, 0x1b,
	0xd8, 0x69, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf6, 0x0c, 0x8e, 0xb1, 0x00, 0x00,
	0x00,
}
