// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: fightgame.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 开始匹配
type StartMatchReq_10001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *StartMatchReq_10001) Reset() {
	*x = StartMatchReq_10001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMatchReq_10001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchReq_10001) ProtoMessage() {}

func (x *StartMatchReq_10001) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchReq_10001.ProtoReflect.Descriptor instead.
func (*StartMatchReq_10001) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{0}
}

func (x *StartMatchReq_10001) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type StartMatchRes_10001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       int32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PlayerIndex []int32 `protobuf:"varint,2,rep,packed,name=playerIndex,proto3" json:"playerIndex,omitempty"`
}

func (x *StartMatchRes_10001) Reset() {
	*x = StartMatchRes_10001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMatchRes_10001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchRes_10001) ProtoMessage() {}

func (x *StartMatchRes_10001) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchRes_10001.ProtoReflect.Descriptor instead.
func (*StartMatchRes_10001) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{1}
}

func (x *StartMatchRes_10001) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StartMatchRes_10001) GetPlayerIndex() []int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return nil
}

//离开游戏
type LeaveRoomReq_10005 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaveRoomReq_10005) Reset() {
	*x = LeaveRoomReq_10005{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomReq_10005) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq_10005) ProtoMessage() {}

func (x *LeaveRoomReq_10005) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq_10005.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq_10005) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{2}
}

// 攻击别人
type AttackTell_20001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 目标
	Num   int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`     // 伤害
}

func (x *AttackTell_20001) Reset() {
	*x = AttackTell_20001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackTell_20001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackTell_20001) ProtoMessage() {}

func (x *AttackTell_20001) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackTell_20001.ProtoReflect.Descriptor instead.
func (*AttackTell_20001) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{3}
}

func (x *AttackTell_20001) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AttackTell_20001) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 回血
type CureTell_20002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *CureTell_20002) Reset() {
	*x = CureTell_20002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CureTell_20002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CureTell_20002) ProtoMessage() {}

func (x *CureTell_20002) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CureTell_20002.ProtoReflect.Descriptor instead.
func (*CureTell_20002) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{4}
}

func (x *CureTell_20002) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 增加护盾
type DefTell_20003 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *DefTell_20003) Reset() {
	*x = DefTell_20003{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefTell_20003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefTell_20003) ProtoMessage() {}

func (x *DefTell_20003) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefTell_20003.ProtoReflect.Descriptor instead.
func (*DefTell_20003) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{5}
}

func (x *DefTell_20003) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 游戏正式开始
type StartGamePush_30001 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *StartGamePush_30001) Reset() {
	*x = StartGamePush_30001{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGamePush_30001) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGamePush_30001) ProtoMessage() {}

func (x *StartGamePush_30001) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGamePush_30001.ProtoReflect.Descriptor instead.
func (*StartGamePush_30001) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{6}
}

func (x *StartGamePush_30001) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 玩家进入
type UserEnterPush_30002 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *UserEnterPush_30002) Reset() {
	*x = UserEnterPush_30002{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterPush_30002) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterPush_30002) ProtoMessage() {}

func (x *UserEnterPush_30002) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterPush_30002.ProtoReflect.Descriptor instead.
func (*UserEnterPush_30002) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{7}
}

func (x *UserEnterPush_30002) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 血量变化
type BloodChangePush_30003 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 目标
	Num   int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`     // 血量变化
}

func (x *BloodChangePush_30003) Reset() {
	*x = BloodChangePush_30003{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BloodChangePush_30003) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodChangePush_30003) ProtoMessage() {}

func (x *BloodChangePush_30003) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodChangePush_30003.ProtoReflect.Descriptor instead.
func (*BloodChangePush_30003) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{8}
}

func (x *BloodChangePush_30003) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BloodChangePush_30003) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 离开游戏
type LeaveRoomReq_30004 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *LeaveRoomReq_30004) Reset() {
	*x = LeaveRoomReq_30004{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fightgame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRoomReq_30004) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq_30004) ProtoMessage() {}

func (x *LeaveRoomReq_30004) ProtoReflect() protoreflect.Message {
	mi := &file_fightgame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq_30004.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq_30004) Descriptor() ([]byte, []int) {
	return file_fightgame_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoomReq_30004) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_fightgame_proto protoreflect.FileDescriptor

var file_fightgame_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x69, 0x67, 0x68, 0x74, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x31, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x31, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x5f, 0x31, 0x30, 0x30, 0x30, 0x35, 0x22, 0x3a, 0x0a, 0x10,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x65, 0x6c, 0x6c, 0x5f, 0x32, 0x30, 0x30, 0x30, 0x31,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x22, 0x0a, 0x0e, 0x43, 0x75, 0x72, 0x65,
	0x54, 0x65, 0x6c, 0x6c, 0x5f, 0x32, 0x30, 0x30, 0x30, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x21, 0x0a, 0x0d,
	0x44, 0x65, 0x66, 0x54, 0x65, 0x6c, 0x6c, 0x5f, 0x32, 0x30, 0x30, 0x30, 0x33, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22,
	0x2d, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x5f, 0x33, 0x30, 0x30, 0x30, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x2b,
	0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x5f,
	0x33, 0x30, 0x30, 0x30, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3f, 0x0a, 0x15, 0x42,
	0x6c, 0x6f, 0x6f, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x75, 0x73, 0x68, 0x5f, 0x33,
	0x30, 0x30, 0x30, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x2a, 0x0a, 0x12,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x5f, 0x33, 0x30, 0x30,
	0x30, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x04, 0x5a, 0x02, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fightgame_proto_rawDescOnce sync.Once
	file_fightgame_proto_rawDescData = file_fightgame_proto_rawDesc
)

func file_fightgame_proto_rawDescGZIP() []byte {
	file_fightgame_proto_rawDescOnce.Do(func() {
		file_fightgame_proto_rawDescData = protoimpl.X.CompressGZIP(file_fightgame_proto_rawDescData)
	})
	return file_fightgame_proto_rawDescData
}

var file_fightgame_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fightgame_proto_goTypes = []interface{}{
	(*StartMatchReq_10001)(nil),   // 0: proto.StartMatchReq_10001
	(*StartMatchRes_10001)(nil),   // 1: proto.StartMatchRes_10001
	(*LeaveRoomReq_10005)(nil),    // 2: proto.LeaveRoomReq_10005
	(*AttackTell_20001)(nil),      // 3: proto.AttackTell_20001
	(*CureTell_20002)(nil),        // 4: proto.CureTell_20002
	(*DefTell_20003)(nil),         // 5: proto.DefTell_20003
	(*StartGamePush_30001)(nil),   // 6: proto.StartGamePush_30001
	(*UserEnterPush_30002)(nil),   // 7: proto.UserEnterPush_30002
	(*BloodChangePush_30003)(nil), // 8: proto.BloodChangePush_30003
	(*LeaveRoomReq_30004)(nil),    // 9: proto.LeaveRoomReq_30004
}
var file_fightgame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fightgame_proto_init() }
func file_fightgame_proto_init() {
	if File_fightgame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fightgame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMatchReq_10001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMatchRes_10001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomReq_10005); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackTell_20001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CureTell_20002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefTell_20003); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGamePush_30001); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnterPush_30002); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BloodChangePush_30003); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fightgame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRoomReq_30004); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fightgame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fightgame_proto_goTypes,
		DependencyIndexes: file_fightgame_proto_depIdxs,
		MessageInfos:      file_fightgame_proto_msgTypes,
	}.Build()
	File_fightgame_proto = out.File
	file_fightgame_proto_rawDesc = nil
	file_fightgame_proto_goTypes = nil
	file_fightgame_proto_depIdxs = nil
}
