// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fightgame.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// msgNo=10001
type CreateRoomReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{0}
}
func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (dst *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(dst, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

func (m *CreateRoomReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// msgNo=10003
type EnterRoomReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomReq) Reset()         { *m = EnterRoomReq{} }
func (m *EnterRoomReq) String() string { return proto.CompactTextString(m) }
func (*EnterRoomReq) ProtoMessage()    {}
func (*EnterRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{1}
}
func (m *EnterRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomReq.Unmarshal(m, b)
}
func (m *EnterRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomReq.Marshal(b, m, deterministic)
}
func (dst *EnterRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomReq.Merge(dst, src)
}
func (m *EnterRoomReq) XXX_Size() int {
	return xxx_messageInfo_EnterRoomReq.Size(m)
}
func (m *EnterRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomReq proto.InternalMessageInfo

func (m *EnterRoomReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// msgNo=10005
type LeaveRoomReq struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomReq) Reset()         { *m = LeaveRoomReq{} }
func (m *LeaveRoomReq) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomReq) ProtoMessage()    {}
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{2}
}
func (m *LeaveRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomReq.Unmarshal(m, b)
}
func (m *LeaveRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomReq.Marshal(b, m, deterministic)
}
func (dst *LeaveRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomReq.Merge(dst, src)
}
func (m *LeaveRoomReq) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomReq.Size(m)
}
func (m *LeaveRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomReq proto.InternalMessageInfo

func (m *LeaveRoomReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// msgNo=10007
type LoginReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{3}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// msgNo=10008
type LoginRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{4}
}
func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (dst *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(dst, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

// msgNo=10009
type LogoutReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{5}
}
func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (dst *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(dst, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

// msgNo = 20001
type MoveTel struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveTel) Reset()         { *m = MoveTel{} }
func (m *MoveTel) String() string { return proto.CompactTextString(m) }
func (*MoveTel) ProtoMessage()    {}
func (*MoveTel) Descriptor() ([]byte, []int) {
	return fileDescriptor_fightgame_46cab682d3c05527, []int{6}
}
func (m *MoveTel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveTel.Unmarshal(m, b)
}
func (m *MoveTel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveTel.Marshal(b, m, deterministic)
}
func (dst *MoveTel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveTel.Merge(dst, src)
}
func (m *MoveTel) XXX_Size() int {
	return xxx_messageInfo_MoveTel.Size(m)
}
func (m *MoveTel) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveTel.DiscardUnknown(m)
}

var xxx_messageInfo_MoveTel proto.InternalMessageInfo

func (m *MoveTel) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MoveTel) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRoomReq)(nil), "proto.CreateRoomReq")
	proto.RegisterType((*EnterRoomReq)(nil), "proto.EnterRoomReq")
	proto.RegisterType((*LeaveRoomReq)(nil), "proto.LeaveRoomReq")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "proto.LoginRes")
	proto.RegisterType((*LogoutReq)(nil), "proto.LogoutReq")
	proto.RegisterType((*MoveTel)(nil), "proto.MoveTel")
}

func init() { proto.RegisterFile("fightgame.proto", fileDescriptor_fightgame_46cab682d3c05527) }

var fileDescriptor_fightgame_46cab682d3c05527 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcb, 0x4c, 0xcf,
	0x28, 0x49, 0x4f, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a,
	0xea, 0x5c, 0xbc, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x41, 0xf9, 0xf9, 0xb9, 0x41, 0xa9, 0x85,
	0x42, 0x62, 0x5c, 0x6c, 0x45, 0xf9, 0xf9, 0xb9, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc,
	0x41, 0x50, 0x9e, 0x92, 0x1a, 0x17, 0x8f, 0x6b, 0x5e, 0x49, 0x6a, 0x11, 0x11, 0xea, 0x7c, 0x52,
	0x13, 0xcb, 0x08, 0x9a, 0x67, 0xc3, 0xc5, 0xe1, 0x93, 0x9f, 0x9e, 0x99, 0x07, 0x52, 0x23, 0xc2,
	0xc5, 0x5a, 0x92, 0x9f, 0x9d, 0x9a, 0x07, 0x56, 0xc2, 0x19, 0x04, 0xe1, 0x08, 0x49, 0x71, 0x71,
	0x94, 0x16, 0xa7, 0x16, 0xe5, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81, 0x25, 0xe0, 0x7c, 0x25, 0x2e,
	0xb8, 0xee, 0x62, 0x25, 0x6e, 0x2e, 0x4e, 0x9f, 0xfc, 0xf4, 0xfc, 0xd2, 0x92, 0xa0, 0xd4, 0x42,
	0x25, 0x55, 0x2e, 0x76, 0xdf, 0xfc, 0xb2, 0xd4, 0x90, 0xd4, 0x1c, 0x21, 0x1e, 0x2e, 0xc6, 0x0a,
	0xb0, 0x89, 0x8c, 0x41, 0x8c, 0x15, 0x20, 0x5e, 0x25, 0xd8, 0x18, 0xc6, 0x20, 0xc6, 0x4a, 0x27,
	0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x18, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x68, 0xaa, 0x59, 0x1d, 0x01, 0x00, 0x00,
}
