// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 命名规范：
// content中的名字结尾必须以下后缀中的一个
// Req = 请求,要求一定有返回着
// Res = Req消息的返回值
// Msg = 服务器主动推送信息
// Tel = 客户端请求，不需要进行回复的消息
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq          int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                           // 消息编号
	Uid          uint64   `protobuf:"fixed64,2,opt,name=uid,proto3" json:"uid,omitempty"`                          // 用户唯一标识符
	BroadcastUid []uint64 `protobuf:"fixed64,3,rep,packed,name=broadcastUid,proto3" json:"broadcastUid,omitempty"` // 需要收到广播的玩家
	// Types that are assignable to Content:
	//	*Message_HbReq
	//	*Message_HbRes
	//	*Message_SuccessRes
	//	*Message_ErrorRes
	//	*Message_LoginReq
	//	*Message_LoginRes
	//	*Message_ServerReq
	//	*Message_MoveTel
	//	*Message_MoveMsg
	//	*Message_EnterRoomReq
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Message) GetBroadcastUid() []uint64 {
	if x != nil {
		return x.BroadcastUid
	}
	return nil
}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *Message) GetHbReq() *HbReq {
	if x, ok := x.GetContent().(*Message_HbReq); ok {
		return x.HbReq
	}
	return nil
}

func (x *Message) GetHbRes() *HbRes {
	if x, ok := x.GetContent().(*Message_HbRes); ok {
		return x.HbRes
	}
	return nil
}

func (x *Message) GetSuccessRes() *Success {
	if x, ok := x.GetContent().(*Message_SuccessRes); ok {
		return x.SuccessRes
	}
	return nil
}

func (x *Message) GetErrorRes() *Error {
	if x, ok := x.GetContent().(*Message_ErrorRes); ok {
		return x.ErrorRes
	}
	return nil
}

func (x *Message) GetLoginReq() *LoginReq {
	if x, ok := x.GetContent().(*Message_LoginReq); ok {
		return x.LoginReq
	}
	return nil
}

func (x *Message) GetLoginRes() *LoginRes {
	if x, ok := x.GetContent().(*Message_LoginRes); ok {
		return x.LoginRes
	}
	return nil
}

func (x *Message) GetServerReq() *ServerReq {
	if x, ok := x.GetContent().(*Message_ServerReq); ok {
		return x.ServerReq
	}
	return nil
}

func (x *Message) GetMoveTel() *MoveTel {
	if x, ok := x.GetContent().(*Message_MoveTel); ok {
		return x.MoveTel
	}
	return nil
}

func (x *Message) GetMoveMsg() *MoveMsg {
	if x, ok := x.GetContent().(*Message_MoveMsg); ok {
		return x.MoveMsg
	}
	return nil
}

func (x *Message) GetEnterRoomReq() *EnterRoomReq {
	if x, ok := x.GetContent().(*Message_EnterRoomReq); ok {
		return x.EnterRoomReq
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_HbReq struct {
	HbReq *HbReq `protobuf:"bytes,9,opt,name=hbReq,proto3,oneof"`
}

type Message_HbRes struct {
	HbRes *HbRes `protobuf:"bytes,10,opt,name=hbRes,proto3,oneof"`
}

type Message_SuccessRes struct {
	SuccessRes *Success `protobuf:"bytes,11,opt,name=successRes,proto3,oneof"`
}

type Message_ErrorRes struct {
	ErrorRes *Error `protobuf:"bytes,12,opt,name=errorRes,proto3,oneof"`
}

type Message_LoginReq struct {
	LoginReq *LoginReq `protobuf:"bytes,13,opt,name=loginReq,proto3,oneof"`
}

type Message_LoginRes struct {
	LoginRes *LoginRes `protobuf:"bytes,14,opt,name=loginRes,proto3,oneof"`
}

type Message_ServerReq struct {
	ServerReq *ServerReq `protobuf:"bytes,15,opt,name=serverReq,proto3,oneof"`
}

type Message_MoveTel struct {
	// LOCK 业务消息写在下面
	MoveTel *MoveTel `protobuf:"bytes,101,opt,name=moveTel,proto3,oneof"`
}

type Message_MoveMsg struct {
	MoveMsg *MoveMsg `protobuf:"bytes,102,opt,name=moveMsg,proto3,oneof"`
}

type Message_EnterRoomReq struct {
	EnterRoomReq *EnterRoomReq `protobuf:"bytes,103,opt,name=EnterRoomReq,proto3,oneof"`
}

func (*Message_HbReq) isMessage_Content() {}

func (*Message_HbRes) isMessage_Content() {}

func (*Message_SuccessRes) isMessage_Content() {}

func (*Message_ErrorRes) isMessage_Content() {}

func (*Message_LoginReq) isMessage_Content() {}

func (*Message_LoginRes) isMessage_Content() {}

func (*Message_ServerReq) isMessage_Content() {}

func (*Message_MoveTel) isMessage_Content() {}

func (*Message_MoveMsg) isMessage_Content() {}

func (*Message_EnterRoomReq) isMessage_Content() {}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x66, 0x69, 0x67, 0x68, 0x74, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x04, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x06,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x06, 0x52, 0x0c, 0x62, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x55, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x68, 0x62, 0x52,
	0x65, 0x71, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x48, 0x62, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x05, 0x68, 0x62, 0x52, 0x65, 0x71, 0x12,
	0x24, 0x0a, 0x05, 0x68, 0x62, 0x52, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x62, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x05,
	0x68, 0x62, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x2d, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x6c, 0x18, 0x65,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x54, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x6c, 0x12,
	0x2a, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x73, 0x67,
	0x48, 0x00, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x39, 0x0a, 0x0c, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x42, 0x08, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []interface{}{
	(*Message)(nil),      // 0: proto.Message
	(*HbReq)(nil),        // 1: proto.HbReq
	(*HbRes)(nil),        // 2: proto.HbRes
	(*Success)(nil),      // 3: proto.Success
	(*Error)(nil),        // 4: proto.Error
	(*LoginReq)(nil),     // 5: proto.LoginReq
	(*LoginRes)(nil),     // 6: proto.LoginRes
	(*ServerReq)(nil),    // 7: proto.ServerReq
	(*MoveTel)(nil),      // 8: proto.MoveTel
	(*MoveMsg)(nil),      // 9: proto.MoveMsg
	(*EnterRoomReq)(nil), // 10: proto.EnterRoomReq
}
var file_message_proto_depIdxs = []int32{
	1,  // 0: proto.Message.hbReq:type_name -> proto.HbReq
	2,  // 1: proto.Message.hbRes:type_name -> proto.HbRes
	3,  // 2: proto.Message.successRes:type_name -> proto.Success
	4,  // 3: proto.Message.errorRes:type_name -> proto.Error
	5,  // 4: proto.Message.loginReq:type_name -> proto.LoginReq
	6,  // 5: proto.Message.loginRes:type_name -> proto.LoginRes
	7,  // 6: proto.Message.serverReq:type_name -> proto.ServerReq
	8,  // 7: proto.Message.moveTel:type_name -> proto.MoveTel
	9,  // 8: proto.Message.moveMsg:type_name -> proto.MoveMsg
	10, // 9: proto.Message.EnterRoomReq:type_name -> proto.EnterRoomReq
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_common_proto_init()
	file_fightgame_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Message_HbReq)(nil),
		(*Message_HbRes)(nil),
		(*Message_SuccessRes)(nil),
		(*Message_ErrorRes)(nil),
		(*Message_LoginReq)(nil),
		(*Message_LoginRes)(nil),
		(*Message_ServerReq)(nil),
		(*Message_MoveTel)(nil),
		(*Message_MoveMsg)(nil),
		(*Message_EnterRoomReq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
